-- ===================================================================================
-- ONLINE AUCTION DATABASE SCHEMA
-- ===================================================================================
-- Description: Complete database schema for Online Auction Platform
-- Author: PTUDW Team
-- Created: 2025
-- Last Updated: 2026-01-07
-- Database: PostgreSQL 14+
-- Charset: UTF8
-- ===================================================================================

BEGIN;

-- ===================================================================================
-- SECTION 1: INITIAL SETUP
-- ===================================================================================

-- 1.1. Set timezone to Vietnam (UTC+7)
SET TIME ZONE 'Asia/Ho_Chi_Minh';

-- 1.2. Drop existing tables and types (for clean reinstall)
-- WARNING: This will delete all data!
DROP TABLE IF EXISTS system_settings CASCADE; 
DROP TABLE IF EXISTS product_comments CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_chats CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS rejected_bidders CASCADE;
DROP TABLE IF EXISTS product_description_updates CASCADE;
DROP TABLE IF EXISTS auto_bidding CASCADE;
DROP TABLE IF EXISTS bidding_history CASCADE;
DROP TABLE IF EXISTS watchlists CASCADE;
DROP TABLE IF EXISTS product_images CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS upgrade_requests CASCADE;
DROP TABLE IF EXISTS user_otps CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS order_status_history CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;

-- Drop custom types
DROP TYPE IF EXISTS request_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS otp_purpose CASCADE;

-- ===================================================================================
-- SECTION 2: USER MANAGEMENT
-- ===================================================================================

-- 2.1. User Role Enum
CREATE TYPE user_role AS ENUM ('bidder', 'seller', 'admin');

-- 2.2. Users Table
-- Stores all user accounts (bidders, sellers, admins)
CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname            VARCHAR(100)      NOT NULL,           -- Full name of user
    address             VARCHAR(255)      NOT NULL,           -- Physical address
    email               VARCHAR(191)      NOT NULL UNIQUE,    -- Email (used for login)
    password_hash       VARCHAR(100),                         -- Hashed password (NULL for OAuth users)
    role                user_role         NOT NULL DEFAULT 'bidder',  -- User role
    
    date_of_birth       DATE,                                 -- Date of birth (optional)
    email_verified      BOOLEAN           NOT NULL DEFAULT FALSE,      -- Email verification status
    is_upgrade_pending  BOOLEAN           NOT NULL DEFAULT FALSE,      -- Pending upgrade to seller
    created_at          TIMESTAMPTZ       NOT NULL DEFAULT NOW(),      -- Account creation timestamp
    updated_at          TIMESTAMPTZ       NOT NULL DEFAULT NOW()       -- Last update timestamp
);

-- 2.3. Auto-update timestamp function
-- This function automatically updates the updated_at field when a row is modified
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2.4. Trigger to auto-update users.updated_at
CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ===================================================================================
-- SECTION 3: AUTHENTICATION & VERIFICATION
-- ===================================================================================

-- 3.1. OTP Purpose Enum
CREATE TYPE otp_purpose AS ENUM ('verify_email', 'reset_password');

-- 3.2. User OTPs Table
-- Stores one-time passwords for email verification and password reset
CREATE TABLE user_otps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    otp_code    VARCHAR(10) NOT NULL,                       -- OTP code (6-10 digits)
    purpose     otp_purpose NOT NULL,                       -- Why OTP was generated
    expires_at  TIMESTAMPTZ NOT NULL,                       -- Expiration time
    used        BOOLEAN     NOT NULL DEFAULT FALSE,         -- Has been used?
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3.3. Upgrade Request Status Enum
CREATE TYPE request_status AS ENUM ('pending', 'approved', 'rejected', 'expired');

-- 3.4. Upgrade Requests Table
-- Tracks bidders requesting upgrade to seller role
CREATE TABLE upgrade_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status request_status NOT NULL DEFAULT 'pending',       -- Request status
    admin_note TEXT,                                        -- Admin's note for rejection/approval
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_requests_status_created ON upgrade_requests(status, created_at);

-- ===================================================================================
-- SECTION 4: PRODUCT CATEGORIES
-- ===================================================================================

-- 4.1. Categories Table
-- Hierarchical category structure (parent-child relationships)
CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,                             -- Category name
    parent_id INT REFERENCES categories(id) ON DELETE SET NULL  -- NULL = root category
);

-- ===================================================================================
-- SECTION 5: PRODUCTS & AUCTIONS
-- ===================================================================================

-- 5.1. Products Table
-- Core table for auction items
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Basic Information
    name TEXT NOT NULL,                                     -- Product name
    thumbnail TEXT,                                         -- Main image URL
    description TEXT,                                       -- Product description
    
    -- Relationships
    category_id INT NOT NULL REFERENCES categories(id),    -- Product category
    seller_id BIGINT NOT NULL REFERENCES users(id),        -- Seller (owner)
    highest_bidder_id BIGINT REFERENCES users(id),         -- Current highest bidder

    -- Pricing & Auction Logic
    starting_price BIGINT NOT NULL CHECK (starting_price >= 0),     -- Starting bid price
    step_price BIGINT NOT NULL CHECK (step_price > 0),              -- Minimum bid increment
    buy_now_price BIGINT CHECK (buy_now_price >= 0),                -- Instant purchase price (optional)
    is_buy_now_purchase BOOLEAN DEFAULT FALSE,                      -- Was bought instantly?
    current_price BIGINT CHECK (current_price >= 0),                -- Current highest bid
    highest_max_price BIGINT DEFAULT NULL CHECK (highest_max_price >= 0),  -- Auto-bidding max
    allow_unrated_bidder BOOLEAN DEFAULT FALSE,                     -- Allow new users to bid?

    -- Time & Status
    created_at TIMESTAMPTZ DEFAULT NOW(),                   -- Creation timestamp
    end_at TIMESTAMPTZ NOT NULL,                            -- Auction end time
    auto_extend BOOLEAN DEFAULT FALSE,                      -- Auto-extend if late bid?
    end_notification_sent TIMESTAMP DEFAULT NULL,           -- Email notification sent?
    is_sold BOOLEAN DEFAULT NULL,                           -- NULL=active, TRUE=sold, FALSE=unsold
    closed_at TIMESTAMPTZ                                   -- When auction closed (sold/expired)
);

-- 5.2. Product Images Table
-- Additional product images (besides thumbnail)
CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    img_link TEXT NOT NULL                                  -- Image URL
);

-- ===================================================================================
-- SECTION 6: BIDDING & WATCHLIST
-- ===================================================================================

-- 6.1. Watchlist Table
-- Products that users are watching/following
CREATE TABLE watchlists (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, product_id)
);

-- 6.2. Bidding History Table
-- Records every bid placed on products
CREATE TABLE bidding_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id),
    current_price BIGINT NOT NULL,                          -- Bid amount
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_buy_now BOOLEAN DEFAULT FALSE                        -- Was this a buy-now purchase?
);
CREATE INDEX idx_bidding_product ON bidding_history(product_id);

-- 6.3. Auto Bidding Table
-- Automatic bidding up to a maximum price
CREATE TABLE auto_bidding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id),
    max_price BIGINT NOT NULL,                              -- Maximum price to bid up to
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, bidder_id)                          -- One auto-bid per user per product
);

-- ===================================================================================
-- SECTION 7: SELLER TOOLS
-- ===================================================================================

-- 7.1. Product Description Updates Table
-- Allows sellers to add additional info after listing
CREATE TABLE product_description_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    content TEXT NOT NULL,                                  -- Additional description
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7.2. Rejected Bidders Table
-- Sellers can block specific bidders from their products
CREATE TABLE IF NOT EXISTS rejected_bidders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    bidder_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rejected_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, bidder_id)                          -- One rejection per bidder per product
);

-- Indexes for faster lookups
CREATE INDEX idx_rejected_bidders_product ON rejected_bidders(product_id);
CREATE INDEX idx_rejected_bidders_bidder ON rejected_bidders(bidder_id);

-- ===================================================================================
-- SECTION 8: REVIEWS & RATINGS
-- ===================================================================================

-- 8.1. Reviews Table
-- Users can rate each other after transaction (+1, 0, -1)
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- References
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users(id),      -- Who is giving the rating
    reviewee_id BIGINT NOT NULL REFERENCES users(id),      -- Who is being rated
    
    -- Rating: +1 (positive), 0 (neutral), -1 (negative)
    rating INT NOT NULL CHECK (rating IN (0, 1, -1)),
    
    -- Optional comment
    comment TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Each user can only review once per product
    UNIQUE (product_id, reviewer_id)
);

CREATE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ===================================================================================
-- SECTION 9: PRODUCT COMMENTS & DISCUSSIONS
-- ===================================================================================

-- 9.1. Product Comments Table
-- Q&A system for products (with nested replies)
CREATE TABLE product_comments (
  id BIGSERIAL PRIMARY KEY,
  product_id BIGINT REFERENCES products(id),
  user_id BIGINT REFERENCES users(id),
  content TEXT NOT NULL,                                    -- Comment text
  parent_id BIGINT REFERENCES product_comments(id),         -- NULL = parent comment, otherwise reply
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===================================================================================
-- SECTION 10: SYSTEM CONFIGURATION
-- ===================================================================================

-- 10.1. System Settings Table
-- Global configuration for auction behavior
CREATE TABLE system_settings (
    id INT PRIMARY KEY DEFAULT 1,                           -- Single row table
    new_product_limit_minutes INT DEFAULT 60,               -- "New" badge duration
    auto_extend_trigger_minutes INT DEFAULT 5,              -- Auto-extend if bid in last X minutes
    auto_extend_duration_minutes INT DEFAULT 10             -- Extend by X minutes
);

COMMIT;



-- ===================================================================================
-- SECTION 11: ORDER MANAGEMENT SYSTEM
-- ===================================================================================

-- 11.1. Order Status Enum
-- Represents the lifecycle of an order from payment to completion
DROP TYPE IF EXISTS order_status_type CASCADE;
CREATE TYPE order_status_type AS ENUM (
    'pending_payment',      -- Waiting for buyer to submit payment proof
    'payment_submitted',    -- Buyer has uploaded payment proof
    'payment_confirmed',    -- Seller confirmed receiving payment
    'shipped',              -- Seller has shipped the item
    'delivered',            -- Buyer confirmed delivery
    'completed',            -- Transaction complete (with rating)
    'cancelled'             -- Order cancelled
);

-- 11.2. Orders Table
-- Main table for tracking post-auction transactions
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Relationships
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES users(id),
    buyer_id BIGINT NOT NULL REFERENCES users(id),          -- Winner of auction
    
    -- Order Information
    final_price BIGINT NOT NULL,                            -- Final auction price
    
    -- Status tracking
    status order_status_type NOT NULL DEFAULT 'pending_payment',
    
    -- Shipping information (provided by buyer)
    shipping_address TEXT,                                  -- Delivery address
    shipping_phone VARCHAR(20),                             -- Contact phone
    shipping_note TEXT,                                     -- Delivery notes
    
    -- Tracking (provided by seller)
    tracking_number VARCHAR(100),                           -- Tracking number
    shipping_provider VARCHAR(100),                         -- Courier company
    
    -- Timestamps for each status
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_submitted_at TIMESTAMPTZ,                       -- When buyer uploaded proof
    payment_confirmed_at TIMESTAMPTZ,                       -- When seller confirmed
    shipped_at TIMESTAMPTZ,                                 -- When seller shipped
    delivered_at TIMESTAMPTZ,                               -- When buyer confirmed delivery
    completed_at TIMESTAMPTZ,                               -- When transaction completed
    cancelled_at TIMESTAMPTZ,                               -- When order cancelled
    
    -- Cancellation information
    cancelled_by BIGINT REFERENCES users(id),               -- Who cancelled
    cancellation_reason TEXT,                               -- Why cancelled
    
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for faster queries
CREATE INDEX idx_orders_product ON orders(product_id);
CREATE INDEX idx_orders_seller ON orders(seller_id);
CREATE INDEX idx_orders_buyer ON orders(buyer_id);
CREATE INDEX idx_orders_status ON orders(status);

-- Auto-update trigger
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ===================================================================================
-- SECTION 12: INVOICES & PAYMENT PROOFS
-- ===================================================================================

-- 12.1. Invoice Type Enum
DROP TYPE IF EXISTS invoice_type CASCADE;
CREATE TYPE invoice_type AS ENUM (
    'payment',              -- Payment proof from buyer
    'shipping'              -- Shipping proof from seller
);

-- 12.2. Payment Method Enum
DROP TYPE IF EXISTS payment_method_type CASCADE;
CREATE TYPE payment_method_type AS ENUM (
    'bank_transfer',        -- Bank transfer
    'cash',                 -- Cash on delivery
    'momo',                 -- MoMo wallet
    'zalopay',              -- ZaloPay
    'other'                 -- Other methods
);

-- 12.3. Invoices Table
-- Stores payment and shipping proofs (images)
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- References
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    issuer_id BIGINT NOT NULL REFERENCES users(id),         -- Who created this invoice
    
    -- Invoice Type
    invoice_type invoice_type NOT NULL,
    
    -- Payment Information (for buyer's payment proof)
    payment_method payment_method_type,                     -- Payment method used
    payment_proof_urls TEXT[],                              -- Array of image URLs (REQUIRED)
    note TEXT,                                              -- Additional notes
    
    -- Shipping Information (for seller's shipping proof)
    tracking_number VARCHAR(100),                           -- Tracking number (REQUIRED)
    shipping_provider VARCHAR(100),                         -- Courier company
    shipping_proof_urls TEXT[],                             -- Shipping receipt images (OPTIONAL)
    
    -- Verification
    is_verified BOOLEAN DEFAULT FALSE,                      -- Has been verified?
    verified_at TIMESTAMPTZ,                                -- When verified
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_invoices_order ON invoices(order_id);
CREATE INDEX idx_invoices_type ON invoices(invoice_type);
CREATE INDEX idx_invoices_issuer ON invoices(issuer_id);

-- Auto-update trigger
CREATE TRIGGER trg_invoices_updated_at
BEFORE UPDATE ON invoices
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ===================================================================================
-- SECTION 13: ORDER STATUS HISTORY & CHAT
-- ===================================================================================

-- 13.1. Order Status History Table
-- Tracks all status changes for audit trail
CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status order_status_type,                          -- Previous status (NULL if first)
    to_status order_status_type NOT NULL,                   -- New status
    
    changed_by BIGINT NOT NULL REFERENCES users(id),        -- Who made the change
    note TEXT,                                              -- Optional note
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_status_history_order ON order_status_history(order_id);

-- 13.2. Order Chats Table
-- Communication between buyer and seller during transaction
CREATE TABLE order_chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    
    message TEXT NOT NULL,                                  -- Chat message
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_chats_order ON order_chats(order_id);
CREATE INDEX idx_order_chats_sender ON order_chats(sender_id);

-- ===================================================================================
-- SECTION 14: TRIGGERS & AUTOMATION
-- ===================================================================================

-- 14.1. Auto-create Order when Auction Ends
-- This function automatically creates an order when:
-- - Auction has ended (end_at <= NOW() OR closed_at IS NOT NULL)
-- - There is a winner (highest_bidder_id IS NOT NULL)
-- - Not yet marked as sold (is_sold IS NULL)
CREATE OR REPLACE FUNCTION create_order_for_pending_product()
RETURNS TRIGGER AS $$
BEGIN
    -- Check conditions for order creation
    IF NEW.highest_bidder_id IS NOT NULL 
       AND NEW.is_sold IS NULL 
       AND (NEW.end_at <= NOW() OR NEW.closed_at IS NOT NULL) THEN
        
        -- Check if order already exists
        IF NOT EXISTS (
            SELECT 1 FROM orders 
            WHERE product_id = NEW.id
        ) THEN
            -- Create new order
            INSERT INTO orders (
                product_id,
                seller_id,
                buyer_id,
                final_price,
                status,
                created_at
            ) VALUES (
                NEW.id,
                NEW.seller_id,
                NEW.highest_bidder_id,
                NEW.current_price,
                'pending_payment',
                NOW()
            );
            
            -- Log status change
            INSERT INTO order_status_history (
                order_id,
                from_status,
                to_status,
                changed_by,
                note,
                created_at
            ) VALUES (
                (SELECT id FROM orders WHERE product_id = NEW.id),
                NULL,
                'pending_payment',
                NEW.highest_bidder_id,
                'Order created automatically when auction ended',
                NOW()
            );
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 14.2. Trigger to execute order creation
DROP TRIGGER IF EXISTS trg_create_order_on_product_end ON products;
CREATE TRIGGER trg_create_order_on_product_end
AFTER UPDATE OR INSERT ON products
FOR EACH ROW
EXECUTE FUNCTION create_order_for_pending_product();

-- ===================================================================================
-- SECTION 15: HELPER FUNCTIONS
-- ===================================================================================

-- 15.1. Get Order Status by Product ID
-- Returns the current status of an order for a given product
CREATE OR REPLACE FUNCTION get_order_status_by_product(p_product_id BIGINT)
RETURNS order_status_type AS $$
DECLARE
    v_status order_status_type;
BEGIN
    SELECT status INTO v_status
    FROM orders
    WHERE product_id = p_product_id
    LIMIT 1;
    
    RETURN v_status;
END;
$$ LANGUAGE plpgsql;

-- 15.2. Check User Access to Order
-- Verifies if a user has permission to view/modify an order
CREATE OR REPLACE FUNCTION can_user_access_order(p_order_id BIGINT, p_user_id BIGINT)
RETURNS BOOLEAN AS $$
DECLARE
    v_can_access BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM orders
        WHERE id = p_order_id
        AND (seller_id = p_user_id OR buyer_id = p_user_id)
    ) INTO v_can_access;
    
    RETURN v_can_access;
END;
$$ LANGUAGE plpgsql;

-- ===================================================================================
-- END OF SCHEMA
-- ===================================================================================

COMMIT;

